### PR TITLE
Feature/icm/834 fix ingress annotation conflict in icm web chart

### LINKED ISSUE #834: ICM: fix ingress annotation conflict in icm-web chart

### PR DESCRIPTION
**Pull request by skiesewetter-intershop**
## PR Type

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] CI-related changes
- [ ] Documentation content changes
- [ ] Application / infrastructure changes

## What Is the Current Behavior?

Issue Number: Closes #834

## Does this PR Introduce a Breaking Change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by DevDavido** [comment]
Target branch `main` instead of `develop/icm` @skiesewetter-intershop?

**Review by tvalchev2 — APPROVED** [review]
Thank you for fixing the ingress annotation. 

It is better if we don't define ingress specific annotations directly in the helmchart, since that binds us to nginx as ingress controller and this cannot be changed easily, if decided to go for another controller

**Comment by skiesewetter-intershop** [comment]
> Target branch `main` instead of `develop/icm` @skiesewetter-intershop?

Oh, like nearly always I selected to wrong branch. But why is no new build triggered if I change the target branch?

**Comment by DevDavido** [comment]
> [...] But why is no new build triggered if I change the target branch?

Our [current workflow triggers](https://github.com/intershop/helm-charts/tree/main/.github/workflows) don't react on such `edited` activity type, but by default only on `open`, `synchronize` and `reopened`:
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request

**Pull request closed without merging**
